version: '3.1'

services:
  clients:
    build: .
    environment:
      DB_DRIVER: "postgres"
      DB_URI: "host=db user=postgres dbname=huskyjam password=suppersecret sslmode=disable"
      REDIS_ADDR: "redis:6379"
      REDIS_MAX_IDLE: 3
      REDIS_IDLE_TIME: 10
      JWT_SECRET: mysuppersecret
      JWT_ACCESS_TTL_MINUTES: 10
      HTTP_PORT: 3000
    depends_on:
      - redis
      - db
    restart: always
    ports:
      - 3000:3000

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=suppersecret
      - POSTGRES_DB=huskyjam
    ports:
      - 5432:5432